[package]
name = "q_learning"
version = "0.1.0"
authors = ["cotton <chinoknct@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
